codecov:
  require_ci_to_pass: true
ignore:
  - "src/index.tsx"
  - "src/serviceWorker.ts"
coverage:
  precision: 2
  round: nearest
  range: "90...100"
  status:
    project:
      default:
        base: auto
        target: auto
        threshold: 0.1%
        if_not_found: success
    backend:
      paths:
        - backend
    frontend:
      paths:
        - src

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
